build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 25
  ComplexCondition:
    threshold: 5
  CyclomaticComplexMethod:
    threshold: 20

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 5
  MaxLineLength:
    maxLineLength: 140
  UnusedPrivateMember:
    active: true
  ForbiddenComment:
    active: false
  WildcardImport:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'
  MatchingDeclarationName:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: true

coroutines:
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: false
